### PR TITLE
Added identifier for package nodes

### PR DESCRIPTION
**Pull request by Rishav159**
The nodes that includes packages will now have '(P)' appended in their filename.

### CODE REVIEW

**Comment by pombredanne** [comment]
@Rishav159 Thanks! @jdaguil your to review

**Comment by pombredanne** [comment]
@Rishav159 could there be another way may be with an icon for the node rather than adding extra characters to the node name?

**Comment by pombredanne** [comment]
@jdaguil what do you think?

**Comment by Rishav159** [comment]
@pombredanne @jdaguil I changed the color of the text-background to green instead of appending '(P)' in the filenames, to identify if the files contain package information. 
Please review.

**Comment by jdaguil** [comment]
Hi @Rishav159 I'll review this soon. For any pull requests, we would want to merge them into the `develop` branch and not `master`.

**Comment by Rishav159** [comment]
@jdaguil Okay. I will make the PR again to the `develop` branch.

**Pull request closed without merging**
