### PR TITLE
Replace default menu with existing custom menu

### PR DESCRIPTION
**Pull request by johnmhoran**
* The existing custom menu is now displayed in development mode, i.e., when npm start is run.
  * main.js was also reformatted to adjust to the code modifications -- note that this reformatting makes the GH diff somewhat confusing.
  * Addresses Issue #53.

Signed-off-by: <johnmhoran@gmail.com>

### CODE REVIEW

**Comment by jdaguil** [comment]
Currently, I only see the main Electron menu item. 

screen shot 2017-04-25 at 1 15 27 pm


Previously I had other menu items such as Edit, View, etc.   

screen shot 2017-04-25 at 1 16 29 pm

**Comment by jdaguil** [comment]
@johnmhoran The latest change brings back the menu items: Edit, View, Window, and Help. Also, the sub-menu links now link to our repo. However, the main menu title is still Electron.

**Comment by johnmhoran** [comment]
Re the 2 commits I pushed approx. 15 minutes ago:

This set of commits displays the existing custom menu in development mode (i.e., when `npm start` is run).  All menu-related code is found in `main.js`.  

The Darwin/OS X platform does not display the `AboutCode Manager` title in the menu bar (`Electron` is displayed instead) – this will be addressed in a separate issue.  Additional enhancements of the custom menu (e.g., a File item with submenu items for JSON import, JSON export and quit, and keyboard shortcuts for these three functions) will also be addressed in separate issues.

**Comment by jdaguil** [comment]
LGTM 👍

**Pull request merged**
